"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
import app.db.base


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=150), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('metric_points',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('throughput_rpm', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version', 'environment', 'timestamp', name='uq_metric_point')
    )
    op.create_index('ix_metric_model_ts', 'metric_points', ['model_id', 'timestamp'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=False),
    sa.Column('training_data_ref', sa.String(length=500), nullable=True),
    sa.Column('artifact_checksum', sa.String(length=80), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("approval_status IN ('PENDING','APPROVED','REJECTED')", name='ck_version_approval'),
    sa.CheckConstraint("stage IN ('DRAFT','VALIDATED','APPROVED','STAGING','PRODUCTION','ARCHIVED','WITHDRAWN')", name='ck_version_stage'),
    sa.CheckConstraint("stage NOT IN ('STAGING','PRODUCTION') OR approval_status = 'APPROVED'", name='ck_version_live_requires_approval'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version')
    )
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_versions_stage'), 'model_versions', ['stage'], unique=False)
    op.create_index('uq_one_production_version', 'model_versions', ['model_id'], unique=True, sqlite_where=sa.text("stage = 'PRODUCTION'"), postgresql_where=sa.text("stage = 'PRODUCTION'"))
    op.create_table('deployments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('simulate_failure', sa.String(length=20), nullable=False),
    sa.Column('failure_class', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('rollback_of', sa.String(length=40), nullable=True),
    sa.Column('request_correlation_id', sa.String(length=64), nullable=True),
    sa.Column('previous_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("environment IN ('dev','staging','production')", name='ck_deployment_environment'),
    sa.CheckConstraint("status IN ('REQUESTED','VALIDATING','DEPLOYING','SUCCEEDED','FAILED','ROLLED_BACK')", name='ck_deployment_status'),
    sa.ForeignKeyConstraint(['model_id', 'version'], ['model_versions.model_id', 'model_versions.version'], name='fk_deployment_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployments_model_env', 'deployments', ['model_id', 'environment'], unique=False)
    op.create_index(op.f('ix_deployments_model_id'), 'deployments', ['model_id'], unique=False)
    op.create_index(op.f('ix_deployments_rollback_of'), 'deployments', ['rollback_of'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index('uq_active_deployment', 'deployments', ['model_id', 'environment'], unique=True, sqlite_where=sa.text("status IN ('REQUESTED','VALIDATING','DEPLOYING')"), postgresql_where=sa.text("status IN ('REQUESTED','VALIDATING','DEPLOYING')"))
    op.create_index('uq_idempotency_scope', 'deployments', ['requested_by', 'idempotency_key'], unique=True)
    op.create_table('environment_state',
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('live_deployment_id', sa.String(length=40), nullable=True),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("environment IN ('dev','staging','production')", name='ck_envstate_environment'),
    sa.ForeignKeyConstraint(['model_id', 'version'], ['model_versions.model_id', 'model_versions.version'], name='fk_envstate_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'environment')
    )
    op.create_table('deployment_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_events_deployment_id'), 'deployment_events', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_events_model_id'), 'deployment_events', ['model_id'], unique=False)
    op.create_index(op.f('ix_deployment_events_timestamp'), 'deployment_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_events_timestamp'), table_name='deployment_events')
    op.drop_index(op.f('ix_deployment_events_model_id'), table_name='deployment_events')
    op.drop_index(op.f('ix_deployment_events_deployment_id'), table_name='deployment_events')
    op.drop_table('deployment_events')
    op.drop_table('environment_state')
    op.drop_index('uq_idempotency_scope', table_name='deployments')
    op.drop_index('uq_active_deployment', table_name='deployments', sqlite_where=sa.text("status IN ('REQUESTED','VALIDATING','DEPLOYING')"), postgresql_where=sa.text("status IN ('REQUESTED','VALIDATING','DEPLOYING')"))
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_rollback_of'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_model_id'), table_name='deployments')
    op.drop_index('ix_deployments_model_env', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('uq_one_production_version', table_name='model_versions', sqlite_where=sa.text("stage = 'PRODUCTION'"), postgresql_where=sa.text("stage = 'PRODUCTION'"))
    op.drop_index(op.f('ix_model_versions_stage'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('models')
    op.drop_index('ix_metric_model_ts', table_name='metric_points')
    op.drop_table('metric_points')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
